import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const spaceMono = Space_Mono({ subsets: ["latin"], weight:["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className}`}>
        <main className=" h-screen bg-emerald-100 flex items-center justify-center" >
          <div className="max-w-screen-md m-auto flex-1 px-4 flex flex-col">
            <div className="rounded-3xl bg-white shadow-lg w-full p-8 flex-1 grid">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
